name: Java Tests with Maven

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Install dependencies wit hmaven install plugin
      run: mvn initialize --file pom.xml
    - name: Test with Maven
      run: mvn test --file pom.xml
